version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - "./artifacts:/docker-entrypoint-initdb.d"
      - "db:/var/lib/postgresql/data"

volumes:
  db: null
