apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "secrets/*").AsSecrets | nindent 2 }}