name: Build image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        default: pbotapps
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache CLI output
        id: cli-cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: v1-cache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: v1-cli-cache-
      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ inputs.registry }}
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to Azure Container Registry
      - name: Build
        uses: ./.github/actions/build
        with:
          registry: format('{0}.azurecr.io', ${{ inputs.registry }})
          repository: ${{ inputs.repository }}
          tag: ${{ inputs.tag }}
