name: Deploy to staging

on:
  push:
    branches:
      - main

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  create-image:
    name: Create images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: meta
            directory: services/meta
            registry: pbotapps
            repository: federation/meta
          - service: pudl
            directory: services/pudl
            registry: pbotapps
            repository: federation/pudl
    steps:
      - uses: actions/checkout@v3
      - name: Cache CLI output
        id: cli-cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: v1-cache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: v1-cli-cache-
      - name: Build
        uses: ./.github/actions/build
        with:
          artifact-name: ${{ matrix.service }}-${{ github.sha }}
          directory: ${{ matrix.directory }}
      - name: Push
        uses: ./.github/actions/push
        with:
          artifact-name: ${{ matrix.service }}-${{ github.sha }}
          credentials: ${{ secrets. AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.sha }}

  deploy-staging:
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: meta
            directory: services/meta
            cluster-name: pudl-kube-web-2
            cluster-rg: pudl-kube-rg
            cluster-ns: test
            values: |
              extraEnv:
                - name: DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "chart.fullname" . }}
                      key: DATASOURCE_PASSWORD
                - name: DATASOURCE_USERNAME
                  value: meta
                - name: DATASOURCE_HOST
                  value: cockroachdb-public
                - name: DATASOURCE_PORT
                  value: 26257
            password: META_DATASOURCE_PASSWORD
          - service: pudl-ui
            directory: services/pudl
            cluster-name: pudl-kube-data-1
            cluster-rg: pudl-kube-rg
            cluster-ns: pudl-test
            values: |
              ingress:
                hosts:
                  - host: pudl-test.portland.gov
                    path: /
                tls:
                  - secretName: pudl-test-portland-gov-tls
                    hosts:
                      - pudl-test.portland.gov
              extraEnv:
                - name: PUDL_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pudl-test-raw-metastore
                      key: POSTGRES_PASSWORD
                - name: PUDL_POSTGRES_HOST
                  value: pudl-test-postgres
                - name: PUDL_POSTGRES_PORT
                  value: 5432
                - name: PUDL_POSTGRES_USERNAME
                  value: hive_admin
    runs-on: ubuntu-latest
    steps:
      - name: Create secrets
        if: matrix.password
        uses: ./.github/actions/secrets-writer
        with:
          variables: |
            DATASOURCE_PASSWORD=${{ secrets[matrix.password] }}
          output: chart/.secrets
      - name: Create values file
        uses: ./.github/actions/merge-values
        with:
          input: chart/values-test.yaml
          output: values.yaml
          values: ${{ matrix.values }}
      - uses: ./.github/actions/deploy
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ matrix.cluster-name }}
          cluster-rg: ${{ matrix.cluster-name }}
          namespace: ${{ matrix.cluster-ns }}
          chart: ./chart
          release-name: ${{ matrix.service }}
          values-file: values.yaml
